apiVersion: v1
kind: Service
metadata:
  name: csye7374-nodeport
spec:
  type: NodePort             
  ports:
  - port: 80              
    targetPort: 6379         
    nodePort: 30123          
  selector:
    app: redis