apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: "redis"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        name: "redis"
    spec:
      containers:
      - name: redis
        image: kubernetes/redis:v1
        ports:
        - name: redis
          containerPort: 6379
          protocol: "TCP"
        resources:
          limits:
            cpu: "0.1"
            memory: "32Mi"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
