apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: redis-sentinel
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
    spec:
      containers:
      - name: sentinel
        image: kubernetes/redis:v1
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - name: redis-sentinel
            containerPort: 26379
            protocol: "TCP"
        resources:
          limits:
            cpu: "0.1"
            memory: "32Mi"
        livenessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 15
          periodSeconds: 20